name: faye_dart
description: Faye is a publish/subscribe messaging protocol that is built on the Bayeux protocol, a messaging system utilized for transporting asynchronous messages over HTTP.
version: 0.1.1+3
homepage: https://github.com/GetStream/stream-feed-flutter/blob/master/packages/faye_dart
repository: https://github.com/GetStream/stream-feed-flutter/blob/master/packages/faye_dart
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  logging: ^1.2.0
  meta: ^1.11.0
  uuid: ^4.3.3
  web_socket_channel: ^2.4.4

dev_dependencies:
  mocktail: ^1.0.3   
  test: ^1.25.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
