name: stream_feed_flutter
description: Stream Feed official Flutter SDK. Build your own chat experience using Dart and Flutter.
version: 0.0.0
homepage: https://getstream.io/
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  chewie: ^1.7.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  rxdart: ^0.27.1
  stream_feed_flutter_core:
    git:
      url: https://github.com/rajan-nonstopio/stream-feed-flutter
      ref: rajan/feat/version
      path: packages/stream_feed_flutter_core
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  video_thumbnail: ^0.5.3

dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: 8156907eecfa812b181a5a729d790f6d399f311b

dev_dependencies:
  # golden_toolkit: ^0.15.0
  mocktail_image_network: ^1.1.0
  nested: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/svgs/
