name: stream_feed_flutter_core
description: Stream Feed official Flutter SDK Core. Build your own feed experience using Dart and Flutter.
version: 0.8.1
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  dio: ^5.4.1
  equatable: ^2.0.5 
  flutter:
    sdk: flutter
  meta: ^1.11.0
  rxdart: ^0.27.1
  stream_feed:
    git:
      url: https://github.com/rajan-nonstopio/stream-feed-flutter
      ref: rajan/feat/version
      path: packages/stream_feed
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
